"""Initial migration.

Revision ID: fe9ed9b473c2
Revises: 
Create Date: 2023-04-22 17:44:48.879137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9ed9b473c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('rooms', sa.String(), nullable=True),
    sa.Column('is_mortgaged', sa.String(), nullable=True),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('building_type', sa.String(), nullable=True),
    sa.Column('count_of_floor', sa.String(), nullable=True),
    sa.Column('square', sa.String(), nullable=True),
    sa.Column('priv_dormitory', sa.String(), nullable=True),
    sa.Column('renovation', sa.String(), nullable=True),
    sa.Column('telephone_type', sa.String(), nullable=True),
    sa.Column('internet_type', sa.String(), nullable=True),
    sa.Column('bathroom_type', sa.String(), nullable=True),
    sa.Column('balcony', sa.String(), nullable=True),
    sa.Column('balcony_glazed', sa.String(), nullable=True),
    sa.Column('door_type', sa.String(), nullable=True),
    sa.Column('parking', sa.String(), nullable=True),
    sa.Column('furniture', sa.String(), nullable=True),
    sa.Column('floor_type', sa.String(), nullable=True),
    sa.Column('ceiling_height', sa.String(), nullable=True),
    sa.Column('security', sa.String(), nullable=True),
    sa.Column('map_complex', sa.String(), nullable=True),
    sa.Column('has_change', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('parameters')
    # ### end Alembic commands ###
